/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewpetugas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Juvetic
 */
public class BuatLaporan extends javax.swing.JPanel {

    /**
     * Creates new form BuatLaporan
     */
    public BuatLaporan() {
        initComponents();
    }
    
    public void addListener(ActionListener e) {
        btnLaporan.addActionListener(e);
    }

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbLaporan = new javax.swing.JComboBox<>();
        btnLaporan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        cbLaporan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Inventaris Proyektor", "Laporan Peminjaman" }));

        btnLaporan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLaporan.setText("Cetak Laporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(cbLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnLaporan)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(cbLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JComboBox<String> cbLaporan;
    // End of variables declaration//GEN-END:variables
}
