/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewpetugas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author lazuardi
 */
public class MenuAnggota extends javax.swing.JPanel {

    /**
     * Creates new form Anggota
     */
    public MenuAnggota() {
        initComponents();
    }

    public JButton getBtnLihatAnggota() {
        return btnLihatAnggota;
    }

    public JButton getBtnTambahAnggota() {
        return btnTambahAnggota;
    }
    
    public void addListener(ActionListener e) {
        btnLihatAnggota.addActionListener(e);
        btnTambahAnggota.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahAnggota = new javax.swing.JButton();
        btnLihatAnggota = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnTambahAnggota.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnTambahAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702215_Add.png"))); // NOI18N
        btnTambahAnggota.setText("Tambah Anggota");

        btnLihatAnggota.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnLihatAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702219_Information.png"))); // NOI18N
        btnLihatAnggota.setText("Lihat Data Anggota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btnTambahAnggota)
                .addGap(45, 45, 45)
                .addComponent(btnLihatAnggota)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahAnggota)
                    .addComponent(btnLihatAnggota))
                .addContainerGap(326, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatAnggota;
    private javax.swing.JButton btnTambahAnggota;
    // End of variables declaration//GEN-END:variables
}
