package viewpetugas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Juvetic
 */
public class MenuProyektor extends javax.swing.JPanel {

    /**
     * Creates new form LihatAnggota
     */
    public MenuProyektor() {
        initComponents();
    }
    
    public void addListener(ActionListener e) {
        btnLihatProyektor.addActionListener(e);
        btnTambahProyektor.addActionListener(e);
    }

    public JButton getBtnLihatProyektor() {
        return btnLihatProyektor;
    }


    public JButton getBtnTambahProyektor() {
        return btnTambahProyektor;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahProyektor = new javax.swing.JButton();
        btnLihatProyektor = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(764, 644));

        btnTambahProyektor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnTambahProyektor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702215_Add.png"))); // NOI18N
        btnTambahProyektor.setText("Tambah Proyektor");

        btnLihatProyektor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnLihatProyektor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702219_Information.png"))); // NOI18N
        btnLihatProyektor.setText("Lihat Data Proyektor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnTambahProyektor)
                .addGap(31, 31, 31)
                .addComponent(btnLihatProyektor)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahProyektor)
                    .addComponent(btnLihatProyektor))
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatProyektor;
    private javax.swing.JButton btnTambahProyektor;
    // End of variables declaration//GEN-END:variables
}
