/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewpetugas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Juvetic
 */
public class MenuPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form LihatAnggota
     */
    public MenuPeminjaman() {
        initComponents();
    }
    
    public void addListener(ActionListener e) {
        btnLihatDataPeminjaman.addActionListener(e);
        btnTambahPeminjaman.addActionListener(e);
    }

    public JButton getBtnLihatDataPeminjaman() {
        return btnLihatDataPeminjaman;
    }

    public JButton getBtnTambahPeminjaman() {
        return btnTambahPeminjaman;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahPeminjaman = new javax.swing.JButton();
        btnLihatDataPeminjaman = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(764, 644));

        btnTambahPeminjaman.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnTambahPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702215_Add.png"))); // NOI18N
        btnTambahPeminjaman.setText("Tambah Peminjaman");

        btnLihatDataPeminjaman.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnLihatDataPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702219_Information.png"))); // NOI18N
        btnLihatDataPeminjaman.setText("Lihat Data Peminjaman");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(btnTambahPeminjaman)
                .addGap(18, 18, 18)
                .addComponent(btnLihatDataPeminjaman)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPeminjaman)
                    .addComponent(btnLihatDataPeminjaman))
                .addContainerGap(348, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatDataPeminjaman;
    private javax.swing.JButton btnTambahPeminjaman;
    // End of variables declaration//GEN-END:variables
}
