/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewpetugas;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Juvetic
 */
public class MenuUtama extends javax.swing.JFrame {

    private CardLayout cardLayout;
    
    public MenuUtama() {
        initComponents();
        cardLayout = new CardLayout();
        mainPanel.setLayout(cardLayout);
        //Set mid
        //http://stackoverflow.com/questions/2442599/how-to-set-jframe-to-appear-centered-regardless-of-monitor-resolution
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getBtnProyektor() {
        return btnProyektor;
    }

    public JButton getBtnPelaporan() {
        return btnPelaporan;
    }

    public JButton getBtnAkunSaya() {
        return btnAkunSaya;
    }

    public JButton getBtnPeminjaman() {
        return btnPeminjaman;
    }

    public JButton getBtnPengembalian() {
        return btnPengembalian;
    }
    
    public void addListener(ActionListener e) {
        btnPelaporan.addActionListener(e);
        btnProyektor.addActionListener(e);
        btnAnggota.addActionListener(e);
        btnPelaporan.addActionListener(e);
        btnAkunSaya.addActionListener(e);
        btnPeminjaman.addActionListener(e);
        btnPengembalian.addActionListener(e);
        btnAnggota.addActionListener(e);
    }

    public JButton getBtnAnggota() {
        return btnAnggota;
    }
    
    

    public void viewErrorMsg(String errorMsg) {
        JOptionPane.showMessageDialog(this, errorMsg);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btnPeminjaman = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnProyektor = new javax.swing.JButton();
        btnAnggota = new javax.swing.JButton();
        btnPelaporan = new javax.swing.JButton();
        btnAkunSaya = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Peminjaman Proyektor");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));

        btnPeminjaman.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702242_Properties - Copy.png"))); // NOI18N
        btnPeminjaman.setText("Peminjaman");

        btnPengembalian.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702242_Properties.png"))); // NOI18N
        btnPengembalian.setText("Pengembalian");

        btnProyektor.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnProyektor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702245_projector.png"))); // NOI18N
        btnProyektor.setText("Proyektor");

        btnAnggota.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461703657_user_accounts.png"))); // NOI18N
        btnAnggota.setText("Anggota");

        btnPelaporan.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnPelaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702227_Text Document.png"))); // NOI18N
        btnPelaporan.setText("Pelaporan");
        btnPelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelaporanActionPerformed(evt);
            }
        });

        btnAkunSaya.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAkunSaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702206_Delete.png"))); // NOI18N
        btnAkunSaya.setText("Keluar");
        btnAkunSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkunSayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProyektor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPelaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAkunSaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnProyektor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnPelaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAkunSaya, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702245_projector.png"))); // NOI18N
        jLabel2.setText("SISTEM INFORMASI PEMINJAMAN PROYEKTOR");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setName(""); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPelaporanActionPerformed

    private void btnAkunSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkunSayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAkunSayaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkunSaya;
    private javax.swing.JButton btnAnggota;
    private javax.swing.JButton btnPelaporan;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btnProyektor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
