/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewpetugas;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Juvetic
 */
public class MenuPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form LihatAnggota
     */
    public MenuPengembalian() {
        initComponents();
    }
    
    public void addListener(ActionListener e) {
        btnLihatPb.addActionListener(e);
        btnTambahPb.addActionListener(e);
    }

    public JButton getBtnLihatPb() {
        return btnLihatPb;
    }

    public JButton getBtnTambahPb() {
        return btnTambahPb;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahPb = new javax.swing.JButton();
        btnLihatPb = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(764, 644));

        btnTambahPb.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnTambahPb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702215_Add.png"))); // NOI18N
        btnTambahPb.setText("Tambah Pengembalian");

        btnLihatPb.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnLihatPb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1461702219_Information.png"))); // NOI18N
        btnLihatPb.setText("Lihat Data Pengembalian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnTambahPb)
                .addGap(18, 18, 18)
                .addComponent(btnLihatPb)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPb)
                    .addComponent(btnLihatPb))
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatPb;
    private javax.swing.JButton btnTambahPb;
    // End of variables declaration//GEN-END:variables
}
