/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewanggota;

import viewpetugas.*;
import configdb.DBConnection;
import controller.Controller;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juvetic
 */
public class LihatPeminjamanAnggota extends javax.swing.JPanel {

    //Membuat Connection, Statement &
    Connection con;
    ResultSet rs;
    Statement stmt;
    
    DBConnection dbcon = new DBConnection();
    DefaultTableModel tabelModel;
    
    public LihatPeminjamanAnggota() {
        initComponents();
        con = dbcon.openConnection();
            try {
                String sql = "SELECT pj_id, pj_tglpinjam, pj_tgljatuhtempo, "
                        + "pj_tglkembali, pj_denda, pj_status, pr_id, us_id "
                        + "FROM t_peminjaman";

                stmt = con.createStatement();
                rs = stmt.executeQuery(sql);

                String nmKolom [] = {"ID Peminjaman","Tgl Pinjam","Tgl Jatuh Tempo",
                    "Tgl Kembali","Denda","Status", "ID Proyektor", "ID Anggota"};
                tabelModel = new javax.swing.table.DefaultTableModel(null, nmKolom);

                while(rs.next()){
                    String id = rs.getString(1);
                    String tglpinjam = rs.getString(2);
                    String tgljatuhtempo = rs.getString(3);
                    String tglkembali = rs.getString(4);
                    String denda = rs.getString(5);
                    String status = rs.getString(6);
                    String idpr = rs.getString(7);
                    String usid = rs.getString(8);

                    tabelModel.addRow(new String []{id, tglpinjam, tgljatuhtempo, 
                        tglkembali, denda, status, idpr, usid});
                }
                tblPeminjaman.setModel(tabelModel);
            } catch (SQLException ex) {
                System.out.println("Data gagal ditampilkan!" + ex);
            }
    }

    public JTable getTblPeminjaman() {
        return tblPeminjaman;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHapus = new javax.swing.JButton();
        cbCari = new javax.swing.JComboBox<>();
        btnUbah = new javax.swing.JButton();
        txCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnHapus.setText("Hapus");

        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pencarian Berdasarkan ID Peminjaman", "Pencarian Berdasarkan ID Anggota" }));
        cbCari.setLightWeightPopupEnabled(false);

        btnUbah.setText("Ubah");

        btnCari.setText("Cari");

        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeminjaman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(240, 275, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextField txCari;
    // End of variables declaration//GEN-END:variables
}
